### ISSUE TITLE
Support for btrfs

### ISSUE THREAD

**Issue by bagbag** [psy0rz/zfs_autobackup#173]
I would highly appreciate if zfs_autobackup would support btrfs. Yeah, the name wouldn't match :sweat_smile:

ZFS and btrfs have a rather large overlapping of their functionality. If you would extract all the snapshot logic into its own layer (if it isn't already), I could imagine that support for btrfs wouldn't be that hard and primarily require different execs and output parsers.

What do you think about this?

**Comment by psy0rz** [comment]
I dont think thats going to happen.

First it would require a major rewrite, abstracting away a lot of the logic.

Second i never used and will never use btrfs simply because i don't trust it and ZFS is better in any way.

If you compare the history of ZFS and btrfs: 

- ZFS was stable and reliable even in the early days, when it still was in beta. This is because it was developed by brilliant engineers at Sun (Jeff Bonwick, Bill Moore and Matthew Ahrens. ), who had years and years of experience.
- BTRFS on the other hand was riddled with problems from the beginning. Dataloss was common for a long time.

I've been using ZFS since the early opensolaris days,  on illumos, smartos, freebsd and linux. I've never ever lost any data or encountered any major issues. 

So i'm not against it, but for now its too much effort to implement in zfs-autobackup for something i wont use it myself.
