### ISSUE TITLE
Change default value of --min-change to 1

### ISSUE THREAD

**Issue by jmidgren** [psy0rz/zfs_autobackup#37]
I'm not sure I got the exact meaning of this flag, but let me give an example so that you can see if my concerns are justified :-). 

If I have a ZFS dataset for my /etc folder and I change a single byte in a small configuration file, then I assume the number of bytes written to register this change will be a very low number. Consequently the dataset will not be considered changed and no snapshot be made. This would mean that I have to remember to set this option to ensure all minor (but perhaps crucial) changes are backed-up.

Wouldn't the safe default for this option thus be 1 rather than 200000 (as with the methods that handle this internally in the python code)? Then you would not risk missing small but important changes to go unnoticed. This option is still very valuable of course, depending on the kind of data the dataset holds it may be great to avoid making snapshots for small changes, but it seem reasonable that users explicitly ask for this behavior than the other way around.

I saw the discussion in #33, and since the number 200000 is still rather arbitrary, 1 also seems like a reasonable default due to the clear distinction between 0 (no changes at all) and 1 (an ever so small change).

---

BTW, I really love this project! I have been looking for similar solutions but none have taken it all the way in the sense that this solution does.

**Comment by psy0rz** [comment]
First of all: Thanks for trying zfs-autobackup. :)
Indeed the 200000 is what we use to backup Proxmox datasets. If a proxmox dataset has been replicated from another node, its important for us to recognize this and not backup the dataset again. However, for some reasons there often are small changes for some reason that should be ignored. 
I briefly looked into this, but i couldnt find out why this was happening. (probably something prox does?) So thats why i choose this arbitrary number, keeping in mind that surely more data changes normally. I never considered things like /etc directories that only have small changes.
When i changed it from hardcoded to configurable, i should have also made it 1 instead of that arbitrary 200000. I will do that now and i will adjust the example for proxmox to reflect this.

**Comment by jmidgren** [comment]
Ah, that makes sense. I'm glad you chose to change it though!
