### ISSUE TITLE
support non-root users

### ISSUE THREAD

**Issue by dkew8** [psy0rz/zfs_autobackup#38]
Currently, the only way to do backups is to allow the root user to log in via ssh. This is not an option in many cases. Therefore, it would be nice to check if we are root at the beginning and escalate the privileges via su/sudo, if we are not.

**Comment by lciti** [comment]
I agree that having root access may not be the best option. Have you consider the following (untested)?

Option1. Use [`zfs allow`](https://www.freebsd.org/doc/handbook/zfs-zfs-allow.html) to delegate a non-root user the ability to create and remove snapshots.

Option 2. This is IMHO good practice anyway to protect the remote system even when the other one is compromised.
1. On the remote host, create a user called (for example) `zfs-backup` with no password.
2. On the local host (the one running `zfs_autobackup`), generate the SSH keys as described on the main page.
3. On the remote host, edit/create the file `/home/zfs-backup/.ssh/authorized_keys` with the following content:
`from="123.123.123.123",command="sudo -E /usr/local/bin/zfs-backup",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa AAAA....`
where `AAAA...` is the public key (that you can find on the local host in the file `id_rsa.pub` created previously) while `123.123.123.123` is the IP of the local host as seen by the remote host (feel free to skip this argument if you are happy to accept connections from all IPs).
4. On the remote host, execute:
`echo "zfs-backup    ALL = NOPASSWD:SETENV: /usr/local/bin/zfs-backup" | sudo tee /etc/sudoers.d/zfs-backup`
5. Create the file `/usr/local/bin/zfs-backup` with content:

        #!/bin/bash
        echo "$SSH_ORIGINAL_COMMAND" >> /tmp/log
        eval $SSH_ORIGINAL_COMMAND

   Then make it executable with `sudo chmod a+x /usr/local/bin/zfs-backup`.

6. Try to run `zfs_autobackup` from the local server to connect to the remote server and see if everything works as expected. Try it for a while, with the options and the pools/filesystems you would normally want to backup, then inspect `/tmp/log`. Finally, replace the `echo ...` line in `/usr/local/bin/zfs-backup` with something that checks if the command received from the `ssh` call is what you expect, otherwise `exit -1` rather than proceeding to the following `eval` line. To give you and idea, I have used this approach with `rsync` and I abort the command `if [ "$SSH_ORIGINAL_COMMAND" != "rsync --server --sender -blogDtpre.iLsfxC . /backup/" ]`.

I hope this helps.

**Comment by psy0rz** [comment]
Its not so easy to add this feature: how would it enter the password if su or sudo asks for it?

Currently what zfs-autobackup is doing is basically "ssh root@server zfs something.."

If it requires input (like a zfs recv), it will just pass that data into the pipe.

Now consider sudo/su: we would have to do something like

"ssh user@server sudo zfs something.."

Then wait for a password prompt (IF it asks for it and its specified somehow?), enter the password, and then pipe our input data. 

@lciti 's solution might work (it needs some polishing/testing i think)

But then again: why not just allow root login via ssh? If you're gonna trust a tool to use commands like zfs destroy, you might as well trust it with root?

Suggestions or tips for a way to do this are welcome off course. :)

**Comment by lciti** [comment]
Hi psy0rz

You do not need to enter any password because of the `NOPASSWD` flag in `/etc/sudoers.d/zfs-backup`.

The extra safety comes from the fact that in the actual command executed, `/usr/local/bin/zfs-backup`, you can decide whether or not the command received over ssh is what you expect and whether to execute it or not. If you are pulling your backup (i.e. the remote server is the sender and your local host is the backup server), you can check whether the argument of the `zfs` command is `send` or `list` etc but forbid `recv` and `destroy`. To give you an idea `/usr/local/bin/zfs-backup` cuold be (untested):

        #!/bin/bash

        # use contents of $SSH_ORIGINAL_COMMAND to replace arguments
        set - $SSH_ORIGINAL_COMMAND

        if [[ "$1 $2" = "zfs send" && ${@:$#} =~ ^(tank/aaa|tank/bbb).*$ ]]; then
            eval $SSH_ORIGINAL_COMMAND
        else
            echo "Not allowed"
            exit -1
        fi

I do not know if in addition to `send` you also need `list or other commands, but this could be easily added.

I hope this helps,
Luca

**Comment by gdevenyi** [comment]
Ansible is pythonic and handles both passing ssh and sudo passwords via its become module:
https://docs.ansible.com/ansible/latest/user_guide/become.html
https://github.com/ansible/ansible/tree/devel/lib/ansible/plugins/become

**Comment by psy0rz** [comment]
that sounds interesting. would we need those dependencies locally (the server that runs zfs-autobackup), or remote (the server we ssh to) ?

**Comment by dkew8** [comment]
> that sounds interesting. would we need those dependencies locally (the server that runs zfs-autobackup), or remote (the server we ssh to) ?

they should be local

**Comment by gdevenyi** [comment]
ansible is completely local in terms of dependencies, the remote host only requires ssh. It appears it uses ``sshpass`` for the ssh authenticate password handling, and its own internal bits for sudo/su

**Comment by dkew8** [comment]
> ansible is completely local in terms of dependencies, the remote host only requires ssh. It appears it uses `sshpass` for the ssh authenticate password handling, and its own internal bits for sudo/su

to be fair, ansible packs the necessary code and sends it to the remote host for execution, so at least there's a dependency on python. also, become modules are executed on the target host

**Comment by lciti** [comment]
I think ansible solves a different problem. The solution I am proposing hardens the remote server (even when the local host is compromised). I am sure ansible cannot do that if it resides entirely on the local server. You would still need to make changes to the remote server to make sure that only certain operations are doable by whoever logs in through ssh (in a way similar to my approach). If the local server has Ansible running with the sudo password for the remote server stored somewhere, anyone breaking into the local server can break into the remote one.
This is not the case with the approach I suggested. Anyone that breaks into the local server can steal the ssh and access the remote server but they will only be able to run `zfs send` and therefore get information that they probably already obtained by breaking into the backup server. They will not be able to do anything else on the remote server (bring it down, steal other data, etc).

**Comment by psy0rz** [comment]
@lciti i think we need to test and document this so we can add it to the README file as an example.

**Comment by lciti** [comment]
Sure, happy to help.
For now we could focus on a backup systems that pulls data (rather than pushing) as it is the recommended way and it's easier to harden.

The only change needed on the python code would be allowing for a different ssh user.

Then, we would need to determine all possible `zfs` commands that the code is executing remotely (`zfs send -opt1 -opt2 tank/aaa`, `zfs send -t ...`, `zfs list ...`, etc) so we can add the right set of checks to the sample `/usr/local/bin/zfs-backup` to make it as restrictive as possible without missing any functionality
I can look at the code and give it a try but feel free to do it if you think it may be easier for you.

**Comment by psy0rz** [comment]
To use a different ssh user for a server you can just specify user@host for --ssh-source or target.

Better would be to add the host to ~/.ssh/ssh_config, among other settings you want for that host. 

Also see https://github.com/psy0rz/zfs_autobackup#specifying-ssh-port-or-options

**Comment by temoto** [comment]
@psy0rz would you accept patch with `sudo ` prefix to ssh commands? (behind option flag, of course)

**Comment by psy0rz** [comment]
I might, if its clean code offcourse. (no hacks, similar proper styling/variable naming)

However: Wouldn't sudo normally ask for passwords?

Also: I dont want to use libraries like the ones in ansible. This is because i want ssh commands to stay transparent and copy/pastable from the debug output. (This wouldn't be possible if we use some library that does ssh/rpc stuff)

**Comment by lciti** [comment]
> However: Wouldn't sudo normally ask for passwords?

Not necessarily. You can set the sudoers file so that it does not ask for a password when a given user executes a given command. For example

    echo "zfs-backup ALL = NOPASSWD:SETENV: /usr/local/bin/zfs-backup" | sudo tee /etc/sudoers.d/zfs-backup
Allows user `zfs-backup` to run `/usr/local/bin/zfs-backup` without requiring a password.

@temoto  Prepending all commands with sudo may not be needed if one executes "sudo zfs-backup" on the remote server. This can be accomplished by editing `.ssh/authorized_keys` to make it prepend sudo to the ssh command. See my [post above](https://github.com/psy0rz/zfs_autobackup/issues/38#issuecomment-619411902).

**Comment by temoto** [comment]
@lciti thank you, I copied parts of your approach. Terrified of `exec $SSH_ORIGINAL_COMMAND` in security context. Hopefully python shlex.split is safer, without shell mechanics in command. It can also function as mbuffer on remote side.

**Comment by lciti** [comment]
@temoto I totally understand. The `if` statement tries to catch the most obvious injection issues but it is still scary. I agree `shlex.split` in python may be a better option. One could write the whole `/usr/local/bin/zfs-backup`in python. In my case, I always sync the same folder on that remote host so I ended up enumerating the few lines that `zfs_autobackup` invokes and only execute the command if it's exactly one of them.

**Comment by psy0rz** [comment]
@temoto well bring it on :)

**Comment by sblive** [comment]
why is this "solved" so weirdly? it allows non-root, but no way to simply prepend "sudo -n --", which would never hurt if the user is already root or even if there is no NOPASSWD sudoers - the "-n" makes it non-interactive and fail.

IMHO the "correct", safe, secure and easy way is to add port and user to ssh config, but prepend everything with "sudo -n --", which should never cause any issues - could you please prepend it everywhere, where root is needed (e.g. not zfs list) or allow a hack to specify a prefix for each cmd (easy fix)? thanks! :)

**Comment by sblive** [comment]
as a crappy proof-of-concept hack i simply replaced `"zfs"` with `"sudo", "-n","--","zfs"` in ZfsDataset.py and it works fine. the cleaner way would be to only add it where necessary and check for non zfs commands which require root too.

**Comment by psy0rz** [comment]
i agree that sudo has its merits compared to other methods, so i've created #293 

however in that case is would do all zpool and zfs commands via sudo perhaps, since some distributions do not have full permissions in /dev/zfs.

you can hack it in, but i would want to have it optional. (--sudo-target and --sudo-source perhaps)

still i first have to work on getting 4.0 ready. (its in the v3.4 branch)
