### ISSUE TITLE
Pattern backup history (e.g. progressive thinning)

### ISSUE THREAD

**Issue by mariusvw** [psy0rz/zfs_autobackup#8]
It would be nice to be able to define a pattern for the backup history.
For example:

- past 5 year, 1 backup each quarter year
- past year, 1 backup every month
- past half-year, 2 backups every month
- past quarter-year, one backup every week
- past month, one backup every day
- past week, one backup every hour
- past day, one backup every quarter hour (insane?)
- past hour, one backup every minute (even more insane?)
- etc etc... ;)

Any suggestions how/where to implement this are welcome. When I have the time I'll be willing to build it just need some confirmation about the idea what is wished to have :)

**Comment by psy0rz** [comment]
i also already wanted this feature, but its not as simple as one might hope. 

it problaby requires a bunch of parameters to configure this, and also a different way of snapshot naming: snapshots should describe how long they should exist. something like:

backupname-12345-4w  

for a snapshot that should exist for 4 weeks.

or something :)

you also might wanna checkout http://www.znapzend.org/ . 

it already does all this and seems to store all config in properties. didnt test it myself yet.

tonight i'm going to add zfs send resuming because i have filesystem thats too big to upload on a slow and bad uplink we have. (something znapzend doesnt have?)

**Comment by psy0rz** [comment]
Coming soon in v3. It was easier than expected. :)

**Comment by psy0rz** [comment]
Fixed in v3: https://github.com/psy0rz/zfs_autobackup/releases/tag/v3.0-beta1
