### ISSUE TITLE
Problem with quotas

### ISSUE THREAD

**Issue by dmshimself** [psy0rz/zfs_autobackup#92]
I had a dataset on the source called OurImages which used to have a quota on it, but has had for a while.  On the target there are also no quotas.  When I do a backup, I get thhe following and any advice appreciated.

#### Synchronising
  [Target] rpool/offsite1/OurData/OurImages@offsite1-20210905114138: resuming
  [Target] rpool/offsite1/OurData/OurImages@offsite1-20210905114138: receiving incremental
! [Target] STDERR > cannot receive resume stream: destination rpool/offsite1/OurData/OurImages space quota exceeded.
! [Target] Command "zfs recv -u -x refreservation -o canmount=noauto -v -s rpool/offsite1/OurData/OurImages" returned exit code 1 (valid codes: [0])
! [Source] OurData/OurImages: FAILED: Last command returned error
! 1 dataset(s) failed!
  zfs-autobackup v3.1 - (c)2021 E.H.Eefting (edwin@datux.nl)

**Comment by Scrin** [comment]
It seems I'm not the only one who ran into this issue.. zfs_autobackup preserves most properties by default, which includes the quota. If you don't want the quota of the source dataset preserved on the target (like you probably don't), you can add `--filter-properties quota` to the command to strip the quota. (you may need to manually remove the already set quotas from the target datasets)

Quota is a bit problematic, since at the target you will likely have much more snapshots, which all count against the quota limit which means the target will most likely hit the quota limit before the source which I don't think is ever the wanted situation. Perhaps the quota should be filtered out by default to prevent running into issues where the backups stop working "unexpectedly" like this.

**Comment by dmshimself** [comment]
Aha that makes sense and the filter-property option has worked very well 
for me.  Many thanks indeed.  I agree that quotas on the two sides of 
the transfer need a bit of thought as for some situations you'd want 
them to be the same nd with others, not so much.  A great hint from you 
and many thanks

**Comment by psy0rz** [comment]
(Strange, the comment from scrin is missing, i'm only seeing it in my email.)

Indeed zfs-autobackup tries to preserve as many properties as possible. It IS a backup afterall, so it should try to backup properties as well.

We could work around it by storing the properties in a different way (for example: use prefixed-property names on the target side). However, my goal was to try to make things transparent and standard: A zfs-autobackup snapshot should behave the same as a backup that was manually made by the administrator. No "magic" involved. 

For this reason i try to make the error output of the zfs-tools as clear as possible, so you can figure out yourself what the problem is, or people with generic zfs-knowledge can help you solve it. :)

I'm always open to suggestions or enhancements off-course, but this is the general goal of zfs-autobackup.

So its up to the administrator to make a conscious decision to filter out properties that are troublesome in some situations.

Also it might be better to use refquota in some cases:
```
     refquota=size|none
       Limits the amount of space a dataset can consume.  This property enforces a hard limit on the amount of space used.  This hard limit does not include space used by descendents, including file sys‐
       tems and snapshots.
```

This way snapshots arent using up quota-space of a user. (which is probably what you actually want)

**Comment by z3ugma** [comment]
I am finding that when I backup container volumes that are made by lxc/proxmox, the `refquota` is not being updated on the backup server.

Scenario: I created a new container in Proxmox with an initial disk size of `8G` on a ZFS volume. 
This zfs volume is backed up using zfs-autobackup 
Then, I later increased the container's disk size to `16G` using the Proxmox dialog: 

<img width="457" alt="image" src="https://github.com/psy0rz/zfs_autobackup/assets/6099983/bdf3b60c-feb7-43c0-a6dc-0313bd4ddfa1">

<img width="325" alt="image" src="https://github.com/psy0rz/zfs_autobackup/assets/6099983/899af91d-174a-4b05-9f06-28542a33d123">


The `refquota` on the source system now says `16G` but the dataset on the backup server is still at `8G` which causes the backup to fail because the volume is out of space.

**Comment by psy0rz** [comment]
I think that perhaps you're "too late", and the backup server is already full. So it cant receive that new snapshot with the updated property?

Try manually overriding it on the backup server via zfs set.

Edwin
